FROM ubuntu:16.04

RUN mkdir -p /usr/src/app

# Copying necessary scripts into docker image
COPY ./ /usr/src/app

# Setting current working directory as /usr/src/app
WORKDIR /usr/src/app

# installing python packages and create directory for application
# Installing Python dependencies required by application
RUN apt-get update && \
    apt-get install -y python3 python3-pip &&\
    pip3 install -r requirements.txt

CMD ["python3", "app.py"]
